=== moradabaz/Videia/xml/videos.xsd
<?xml version ="1.0" encoding ="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.videos.es/tds" xmlns="http://www.videos.es/tds"
	elementFormDefault="qualified">
	
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="video" type="Video" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="Video">
		<xs:sequence>
			<xs:element name="etiqueta" type="Etiqueta" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="titulo" type="xs:string" use="required" />
		<xs:attribute name="url" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="Etiqueta">
		<xs:attribute name="nombre" type="xs:string" use="required" />
	</xs:complexType>

</xs:schema>

=== moradabaz/Videia/xml/Fichero.xml
<videos xmlns="http://www.videos.es/tds" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
        xs:schemaLocation="http://www.videos.es/tds videos.xsd">
    <video titulo="Luis Fonsi - Sola" url="https://www.youtube.com/watch?v=sKlA0A3ufpc" >
        <etiqueta nombre="Reggaeton"/>
        <etiqueta nombre="Music"/>
    </video>
    <video titulo="Daft Punk - Instant Crush" url="https://www.youtube.com/watch?v=a5uQMwRMHcs">
        <etiqueta nombre="Music"/>
        <etiqueta nombre="Electro"/>
    </video>
    <video titulo="Daft Punk ft Pharrell Williams - Get Lucky" url="https://www.youtube.com/watch?v=5NV6Rdv1a3I" >
        <etiqueta nombre="Electro" />
    </video>
</videos>

=== moradabaz/Videia/xml/videos.xml
<?xml version="1.0" ?>
<videos xmlns="http://www.videos.es/tds" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
	xs:schemaLocation="http://www.videos.es/tds videos.xsd">
	<video titulo="Top 5 Hidden Indie Gems of October 2018" url="https://www.youtube.com/watch?v=4uiaZhgren4" >
		<etiqueta nombre="games"/>
		<etiqueta nombre="indie"/>
	</video>
    <video titulo="The DÃ¸ I A Take Away Show" url="https://www.youtube.com/watch?v=qu577tNp1hA" >
        <etiqueta nombre="music"/>
        <etiqueta nombre="blogotheque"/>
        <etiqueta nombre="solo"/>
    </video>
    <video titulo="Pay Attention - 'Dangerous Business' Preview | Star Wars Resistance" url="https://www.youtube.com/watch?v=R5NyB_bAZI8" >
        <etiqueta nombre="cartoon"/>
        <etiqueta nombre="StarWars"/>
    </video>
    <video titulo="Star Wars The Clone Wars - Master Yoda Vs Droid Battalion [1080p]" url="https://www.youtube.com/watch?v=qTktSFh1UJA" >
        <etiqueta nombre="cartoon"/>
        <etiqueta nombre="StarWars"/>
    </video>
    <video titulo="Gandalf 10 hours" url="https://www.youtube.com/watch?v=G1IbRujko-A">
        <etiqueta nombre="Chilling"/>
    </video>
 </videos>
